# Generated by Django 5.0 on 2024-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('university_name', models.TextField()),
                ('signup_using', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
    ]
