# Generated by Django 4.2.7 on 2024-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_userprofile_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='university_name',
            field=models.TextField(default=None),
        ),
    ]
